/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AylaRouteImport } from './routes/ayla'
import { Route as ImpactRouteRouteImport } from './routes/impact/route'
import { Route as VideosRouteImport } from './routes/videos'
import { Route as ZakatRouteImport } from './routes/zakat'
import { Route as ImpactIndexRouteImport } from './routes/impact/index'
import { Route as ImpactSlugRouteRouteImport } from './routes/impact/$slug/route'
import { Route as ImpactSlugIndexRouteImport } from './routes/impact/$slug/index'
import { Route as ImpactSlugThanksRouteImport } from './routes/impact/$slug/thanks'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AylaRoute = AylaRouteImport.update({
  id: '/ayla',
  path: '/ayla',
  getParentRoute: () => rootRouteImport,
} as any)
const ImpactRouteRoute = ImpactRouteRouteImport.update({
  id: '/impact',
  path: '/impact',
  getParentRoute: () => rootRouteImport,
} as any)
const VideosRoute = VideosRouteImport.update({
  id: '/videos',
  path: '/videos',
  getParentRoute: () => rootRouteImport,
} as any)
const ZakatRoute = ZakatRouteImport.update({
  id: '/zakat',
  path: '/zakat',
  getParentRoute: () => rootRouteImport,
} as any)
const ImpactIndexRoute = ImpactIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ImpactRouteRoute,
} as any)
const ImpactSlugRouteRoute = ImpactSlugRouteRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ImpactRouteRoute,
} as any)
const ImpactSlugIndexRoute = ImpactSlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ImpactSlugRouteRoute,
} as any)
const ImpactSlugThanksRoute = ImpactSlugThanksRouteImport.update({
  id: '/thanks',
  path: '/thanks',
  getParentRoute: () => ImpactSlugRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/impact': typeof ImpactRouteRouteWithChildren
  '/ayla': typeof AylaRoute
  '/videos': typeof VideosRoute
  '/zakat': typeof ZakatRoute
  '/impact/$slug': typeof ImpactSlugRouteRouteWithChildren
  '/impact/': typeof ImpactIndexRoute
  '/impact/$slug/thanks': typeof ImpactSlugThanksRoute
  '/impact/$slug/': typeof ImpactSlugIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ayla': typeof AylaRoute
  '/videos': typeof VideosRoute
  '/zakat': typeof ZakatRoute
  '/impact': typeof ImpactIndexRoute
  '/impact/$slug/thanks': typeof ImpactSlugThanksRoute
  '/impact/$slug': typeof ImpactSlugIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/impact': typeof ImpactRouteRouteWithChildren
  '/ayla': typeof AylaRoute
  '/videos': typeof VideosRoute
  '/zakat': typeof ZakatRoute
  '/impact/$slug': typeof ImpactSlugRouteRouteWithChildren
  '/impact/': typeof ImpactIndexRoute
  '/impact/$slug/thanks': typeof ImpactSlugThanksRoute
  '/impact/$slug/': typeof ImpactSlugIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/impact'
    | '/ayla'
    | '/videos'
    | '/zakat'
    | '/impact/$slug'
    | '/impact/'
    | '/impact/$slug/thanks'
    | '/impact/$slug/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ayla'
    | '/videos'
    | '/zakat'
    | '/impact'
    | '/impact/$slug/thanks'
    | '/impact/$slug'
  id:
    | '__root__'
    | '/'
    | '/impact'
    | '/ayla'
    | '/videos'
    | '/zakat'
    | '/impact/$slug'
    | '/impact/'
    | '/impact/$slug/thanks'
    | '/impact/$slug/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ImpactRouteRoute: typeof ImpactRouteRouteWithChildren
  AylaRoute: typeof AylaRoute
  VideosRoute: typeof VideosRoute
  ZakatRoute: typeof ZakatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ayla': {
      id: '/ayla'
      path: '/ayla'
      fullPath: '/ayla'
      preLoaderRoute: typeof AylaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/impact': {
      id: '/impact'
      path: '/impact'
      fullPath: '/impact'
      preLoaderRoute: typeof ImpactRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/videos': {
      id: '/videos'
      path: '/videos'
      fullPath: '/videos'
      preLoaderRoute: typeof VideosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/zakat': {
      id: '/zakat'
      path: '/zakat'
      fullPath: '/zakat'
      preLoaderRoute: typeof ZakatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/impact/': {
      id: '/impact/'
      path: '/'
      fullPath: '/impact/'
      preLoaderRoute: typeof ImpactIndexRouteImport
      parentRoute: typeof ImpactRouteRoute
    }
    '/impact/$slug': {
      id: '/impact/$slug'
      path: '/$slug'
      fullPath: '/impact/$slug'
      preLoaderRoute: typeof ImpactSlugRouteRouteImport
      parentRoute: typeof ImpactRouteRoute
    }
    '/impact/$slug/': {
      id: '/impact/$slug/'
      path: '/'
      fullPath: '/impact/$slug/'
      preLoaderRoute: typeof ImpactSlugIndexRouteImport
      parentRoute: typeof ImpactSlugRouteRoute
    }
    '/impact/$slug/thanks': {
      id: '/impact/$slug/thanks'
      path: '/thanks'
      fullPath: '/impact/$slug/thanks'
      preLoaderRoute: typeof ImpactSlugThanksRouteImport
      parentRoute: typeof ImpactSlugRouteRoute
    }
  }
}

interface ImpactSlugRouteRouteChildren {
  ImpactSlugThanksRoute: typeof ImpactSlugThanksRoute
  ImpactSlugIndexRoute: typeof ImpactSlugIndexRoute
}

const ImpactSlugRouteRouteChildren: ImpactSlugRouteRouteChildren = {
  ImpactSlugThanksRoute: ImpactSlugThanksRoute,
  ImpactSlugIndexRoute: ImpactSlugIndexRoute,
}

const ImpactSlugRouteRouteWithChildren = ImpactSlugRouteRoute._addFileChildren(
  ImpactSlugRouteRouteChildren,
)

interface ImpactRouteRouteChildren {
  ImpactSlugRouteRoute: typeof ImpactSlugRouteRouteWithChildren
  ImpactIndexRoute: typeof ImpactIndexRoute
}

const ImpactRouteRouteChildren: ImpactRouteRouteChildren = {
  ImpactSlugRouteRoute: ImpactSlugRouteRouteWithChildren,
  ImpactIndexRoute: ImpactIndexRoute,
}

const ImpactRouteRouteWithChildren = ImpactRouteRoute._addFileChildren(
  ImpactRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ImpactRouteRoute: ImpactRouteRouteWithChildren,
  AylaRoute: AylaRoute,
  VideosRoute: VideosRoute,
  ZakatRoute: ZakatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
